# estimation.bayes


from __future__ import annotations

from typing import Dict, Tuple

import json
import os

import numpy as np
import tensorflow as tf
import tensorflow_probability as tfp

from risky_debt.config import ModelParams

from .filters import (
    bootstrap_pf_loglik_lnz,
    importance_sampler_loglik_lnz,
)

tfd = tfp.distributions
tfb = tfp.bijectors


def _make_priors(mp: ModelParams) -> Dict[str, tfd.Distribution]:
    """Priors matching the plan stated in the report."""
    return {
        # theta in (0,1)
        "theta": tfd.Beta(concentration1=2.0, concentration0=2.0),
        # rho in (0,1): logit-normal centered around 0.95
        "rho": tfd.TransformedDistribution(
            distribution=tfd.Normal(
                loc=tf.math.log(0.95) - tf.math.log(1.0 - 0.95), scale=0.35
            ),
            bijector=tfb.Sigmoid(),
        ),
        # sigma_eps > 0: lognormal around 0.07
        "sigma_eps": tfd.LogNormal(loc=tf.math.log(0.07), scale=0.5),
        # psi0 > 0: lognormal around baseline
        "psi0": tfd.LogNormal(loc=tf.math.log(float(mp.psi0)), scale=1.0),
        # alpha in (0,1)
        "alpha": tfd.Beta(concentration1=2.0, concentration0=8.0),
    }


def _extract_observed_lnz(data: Dict[str, np.ndarray]) -> np.ndarray:
    """Get an observed ln z time series from the synthetic dataset.

    The dataset produced by estimation.smm.forward_simulate_dataset is flat (stacked over
    time and paths). For filtering, we need a single time series. Here we take the first
    path (by slicing in blocks) using the stored z, assuming the data is generated by the
    forward simulator which stacks time-major.
    """

    # If caller already provides lnz in the dataset, use it.
    if "lnz" in data:
        return np.asarray(data["lnz"], dtype=np.float32)

    z = np.asarray(data["z"], dtype=np.float32)
    z = np.maximum(z, 1e-12)
    return np.log(z).astype(np.float32)


def _log_joint(
    u: tf.Tensor,
    y_lnz: tf.Tensor,
    priors: Dict[str, tfd.Distribution],
    num_particles: int,
    obs_sigma_lnz: float,
    seed: int,
    kernel: str,
) -> tf.Tensor:
    """Unnormalized log posterior.

    u: unconstrained vector, shape (..., 5)
    """
    u = tf.convert_to_tensor(u, dtype=tf.float32)

    # Transform unconstrained -> constrained parameters
    theta = tf.sigmoid(u[..., 0])
    rho = tf.sigmoid(u[..., 1])
    sigma_eps = tf.nn.softplus(u[..., 2]) + 1e-6
    psi0 = tf.nn.softplus(u[..., 3]) + 1e-6
    alpha = tf.sigmoid(u[..., 4])

    # Prior log-density
    lp = (
        priors["theta"].log_prob(theta)
        + priors["rho"].log_prob(rho)
        + priors["sigma_eps"].log_prob(sigma_eps)
        + priors["psi0"].log_prob(psi0)
        + priors["alpha"].log_prob(alpha)
    )

    # Likelihood via filtering on ln z
    sigma_obs = tf.convert_to_tensor(obs_sigma_lnz, dtype=tf.float32)

    # We use a differentiable estimator for HMC and a standard PF for RWM.
    if kernel == "hmc":
        ll = importance_sampler_loglik_lnz(
            y_lnz=y_lnz,
            rho=rho,
            sigma_eps=sigma_eps,
            sigma_obs=sigma_obs,
            num_particles=num_particles,
            seed=seed,
        )
    else:
        ll, _ = bootstrap_pf_loglik_lnz(
            y_lnz=y_lnz,
            rho=rho,
            sigma_eps=sigma_eps,
            sigma_obs=sigma_obs,
            num_particles=num_particles,
            seed=seed,
        )

    return lp + ll


def estimate_hmc(
    out_dir: str,
    mp_true: ModelParams,
    data: Dict[str, np.ndarray],
    kernel: str = "rwm",
    num_results: int = 200,
    num_burnin: int = 200,
    num_chains: int = 2,
    step_size: float = 0.03,
    num_particles: int = 256,
    obs_sigma_lnz: float = 0.02,
    seed: int = 123,
) -> Dict[str, object]:
    """Run Bayesian estimation and save results.

    This function extracts an observed ln z series from the synthetic dataset
       runs HMC
       saves chain draws and metrics to JSON
    """

    os.makedirs(out_dir, exist_ok=True)

    # Observed ln z
    y_lnz_np = _extract_observed_lnz(data)
    # Use a manageable length (avoid massive stacked arrays)
    # If the dataset is flat, it can be huge. Keep first 300 points by default.

    # Keep likelihood evaluation short for CPU + pytest smoke tests.
    max_T = 40  # keep it small to save time
    if y_lnz_np.shape[0] > max_T:
        y_lnz_np = y_lnz_np[:max_T]

    # if y_lnz_np.shape[0] > 300:
    # y_lnz_np = y_lnz_np[:300]
    y_lnz = tf.convert_to_tensor(y_lnz_np, dtype=tf.float32)

    priors = _make_priors(mp_true)

    # Initial state (unconstrained)
    init_u = tf.zeros((num_chains, 5), dtype=tf.float32)

    def target_log_prob_fn(u: tf.Tensor) -> tf.Tensor:
        return _log_joint(
            u=u,
            y_lnz=y_lnz,
            priors=priors,
            num_particles=int(num_particles),
            obs_sigma_lnz=float(obs_sigma_lnz),
            seed=int(seed),
            kernel=kernel,
        )

    # Kernel selection
    if kernel == "hmc":
        base_kernel = tfp.mcmc.HamiltonianMonteCarlo(
            target_log_prob_fn=target_log_prob_fn,
            step_size=step_size,
            num_leapfrog_steps=5,
        )
        # Adapt step size automatically
        kernel_obj = tfp.mcmc.SimpleStepSizeAdaptation(
            base_kernel,
            num_adaptation_steps=int(0.8 * num_burnin),
            target_accept_prob=0.65,
        )
    else:
        # Robust default: random-walk metropolis
        kernel_obj = tfp.mcmc.RandomWalkMetropolis(
            target_log_prob_fn=target_log_prob_fn,
            new_state_fn=tfp.mcmc.random_walk_normal_fn(scale=step_size),
        )

    draws_u, kernel_results = tfp.mcmc.sample_chain(
        num_results=num_results,
        num_burnin_steps=num_burnin,
        current_state=init_u,
        kernel=kernel_obj,
        # Keep trace minimal to avoid shape issues in TFP's internal trace_scan.
        # this reports error before I fix it
        trace_fn=lambda *_: (),
        seed=seed,
    )

    # Transform draws to constrained parameters for reporting
    theta = tf.sigmoid(draws_u[..., 0]).numpy()
    rho = tf.sigmoid(draws_u[..., 1]).numpy()
    sigma_eps = (tf.nn.softplus(draws_u[..., 2]) + 1e-6).numpy()
    psi0 = (tf.nn.softplus(draws_u[..., 3]) + 1e-6).numpy()
    alpha = tf.sigmoid(draws_u[..., 4]).numpy()

    # Posterior summaries (mean over draws and chains)
    def _mean(x: np.ndarray) -> float:
        return float(np.mean(x))

    post_mean = {
        "theta": _mean(theta),
        "rho": _mean(rho),
        "sigma_eps": _mean(sigma_eps),
        "psi0": _mean(psi0),
        "alpha": _mean(alpha),
    }

    # Comparison metrics (saved + printed)
    true_params = {
        "theta": float(mp_true.theta),
        "rho": float(mp_true.rho),
        "sigma_eps": float(mp_true.sigma_eps),
        "psi0": float(mp_true.psi0),
        "alpha": float(mp_true.alpha),
    }
    param_error = {k: abs(post_mean[k] - true_params[k]) for k in true_params}

    # Filtering diagnostics: evaluate PF loglik at posterior mean (bootstrap PF)
    ll_mean, diags = bootstrap_pf_loglik_lnz(
        y_lnz=y_lnz,
        rho=tf.convert_to_tensor(post_mean["rho"], tf.float32),
        sigma_eps=tf.convert_to_tensor(post_mean["sigma_eps"], tf.float32),
        sigma_obs=tf.convert_to_tensor(obs_sigma_lnz, tf.float32),
        num_particles=int(num_particles),
        seed=int(seed) + 999,
    )

    # Save draws
    draws_path = os.path.join(out_dir, "hmc_draws.npz")
    np.savez_compressed(
        draws_path,
        theta=theta,
        rho=rho,
        sigma_eps=sigma_eps,
        psi0=psi0,
        alpha=alpha,
    )

    results = {
        "method": "HMC",
        "kernel": kernel,
        "num_results": int(num_results),
        "num_burnin": int(num_burnin),
        "num_chains": int(num_chains),
        "step_size": float(step_size),
        "num_particles": int(num_particles),
        "obs_sigma_lnz": float(obs_sigma_lnz),
        "posterior_mean": post_mean,
        "true_params": true_params,
        "ParamError": param_error,
        "loglik_at_post_mean": float(ll_mean.numpy()),
        "pf_diagnostics": {
            "ess_min": float(diags.ess_min.numpy()),
            "ess_mean": float(diags.ess_mean.numpy()),
            "num_resamples": int(diags.num_resamples.numpy()),
        },
        "draws_path": draws_path,
    }

    out_json = os.path.join(out_dir, "hmc_results.json")
    with open(out_json, "w", encoding="utf-8") as f:
        json.dump(results, f, indent=2)

    return results
