from __future__ import annotations

"""Moments + CRN simulation helpers for SMM / GMM.

Key requirement (your requirement #2):
- Synthetic data is generated by *forward policy simulation*.
  That is exactly what `simulate_paths_crn()` does:
    (k_t, z_t) --policy--> k_{t+1}, and AR(1) shocks drive z_{t+1}.

Design goals:
1) Synthetic data generation reuses the same model primitives and policy net.
2) CRN: pre-generate initial states + standard-normal shocks and reuse for each evaluation.
3) Keep code simple and well-commented so it's easy to maintain.
"""

from dataclasses import dataclass
from typing import Dict, Optional, Tuple

import numpy as np
import tensorflow as tf

from ..config import ModelParams
from ..networks import PolicyNet


# -----------------------------
# CRN (Common Random Numbers)
# -----------------------------

@dataclass(frozen=True)
class CRNDesign:
    """Reusable random draws for reproducible simulation.

    - init_k, init_z: shape [N_paths]
    - eps_std_norm:   shape [N_paths, T]  (standard normal shocks)

    We store shocks as N(0,1). For any candidate sigma_eps, we scale:
        eps = sigma_eps * eps_std_norm

    So the *same* underlying randomness is reused even if sigma_eps changes.
    """

    init_k: np.ndarray
    init_z: np.ndarray
    eps_std_norm: np.ndarray

    @property
    def n_paths(self) -> int:
        return int(self.init_k.shape[0])

    @property
    def T(self) -> int:
        return int(self.eps_std_norm.shape[1])


@dataclass(frozen=True)
class PathDataset:
    """Simulated trajectories.

    k: shape [N_paths, T+1]
    z: shape [N_paths, T+1]
    """

    k: np.ndarray
    z: np.ndarray

    def __post_init__(self) -> None:
        if self.k.ndim != 2 or self.z.ndim != 2:
            raise ValueError("k and z must be 2D arrays [N_paths, T+1]")
        if self.k.shape != self.z.shape:
            raise ValueError("k and z must have the same shape")

    @property
    def T(self) -> int:
        return int(self.k.shape[1] - 1)

    @property
    def k_curr(self) -> np.ndarray:
        return self.k[:, :-1]

    @property
    def k_next(self) -> np.ndarray:
        return self.k[:, 1:]

    @property
    def z_curr(self) -> np.ndarray:
        return self.z[:, :-1]

    @property
    def z_next(self) -> np.ndarray:
        return self.z[:, 1:]


def make_crn_design(
    *,
    n_paths: int,
    T: int,
    seed: int,
    k0_low: float = 0.5,
    k0_high: float = 2.0,
    z0_low: float = 0.5,
    z0_high: float = 2.0,
) -> CRNDesign:
    """Create reusable initial states + standard-normal shocks."""
    rng = np.random.default_rng(seed)
    init_k = rng.uniform(k0_low, k0_high, size=(n_paths,)).astype(np.float32)
    init_z = rng.uniform(z0_low, z0_high, size=(n_paths,)).astype(np.float32)
    eps_std = rng.standard_normal(size=(n_paths, T)).astype(np.float32)
    return CRNDesign(init_k=init_k, init_z=init_z, eps_std_norm=eps_std)


# ---------------------------------------
# Forward policy simulation (synthetic data)
# ---------------------------------------

def simulate_paths_crn(
    *,
    policy: PolicyNet,
    mp: ModelParams,
    design: CRNDesign,
    burn_in: int = 0,
    clip_z_min: float = 1e-12,
) -> PathDataset:
    """Forward-simulate (k,z) trajectories under a policy using CRN shocks.

    This is exactly the "forward policy simulation" you said you will use.

    Transition:
      k_{t+1} = policy(k_t, z_t)
      z_{t+1} = exp( rho log z_t + sigma_eps * eps_std_norm )

    We also clip:
      - k_{t+1} into [k_min, k_max]
      - z_t inside log() to avoid NaNs
    """
    if burn_in < 0:
        raise ValueError("burn_in must be >= 0")
    if burn_in >= design.T:
        raise ValueError("burn_in must be < T")

    k = tf.convert_to_tensor(design.init_k, dtype=tf.float32)  # [N]
    z = tf.convert_to_tensor(design.init_z, dtype=tf.float32)  # [N]
    eps_std = tf.convert_to_tensor(design.eps_std_norm, dtype=tf.float32)  # [N,T]

    ks = [k]
    zs = [z]

    rho = tf.constant(mp.rho, tf.float32)
    sigma = tf.constant(mp.sigma_eps, tf.float32)

    k_min = tf.constant(mp.k_min, tf.float32)
    k_max = tf.constant(mp.k_max, tf.float32)

    for t in range(design.T):
        x = tf.stack([k, z], axis=1)  # [N,2]
        k_next = tf.clip_by_value(policy(x), k_min, k_max)

        z_safe = tf.maximum(z, tf.constant(clip_z_min, tf.float32))
        eps = sigma * eps_std[:, t]
        z_next = tf.exp(rho * tf.math.log(z_safe) + eps)

        k, z = k_next, z_next
        ks.append(k)
        zs.append(z)

    k_path = tf.stack(ks, axis=1).numpy().astype(np.float32)  # [N,T+1]
    z_path = tf.stack(zs, axis=1).numpy().astype(np.float32)  # [N,T+1]

    if burn_in > 0:
        k_path = k_path[:, burn_in:]
        z_path = z_path[:, burn_in:]

    return PathDataset(k=k_path, z=z_path)


# ----------------------------
# SMM moments
# ----------------------------

@dataclass(frozen=True)
class MomentSpec:
    """Which moments to compute (ordered names)."""

    names: Tuple[str, ...]


def build_default_moment_spec() -> MomentSpec:
    """Default SMM moments.

    Key change: we include *shock-identification* moments that directly pin down
    (rho, sigma_eps) from the AR(1) law in logs:

        log z_{t+1} = rho * log z_t + eps_{t+1}

    This prevents the outer optimizer from "cheating" by collapsing sigma_eps.
    """
    return MomentSpec(
        names=(
            "corr_logz_t1_t",
            "var_logz",
            "var_dlogz",
            "mean_eps_hat",
            "var_eps_hat",
            "mean_I_over_k",
            "var_I_over_k",
            "var_dlogk",
            "corr_Ioverk_logz",
        )
    )


def _corr(a: np.ndarray, b: np.ndarray) -> float:
    """Simple correlation without external dependencies."""
    a = np.asarray(a).ravel()
    b = np.asarray(b).ravel()
    a = a - a.mean()
    b = b - b.mean()
    denom = (np.sqrt(np.mean(a * a)) * np.sqrt(np.mean(b * b)))
    if denom <= 0:
        return float("nan")
    return float(np.mean(a * b) / denom)


def compute_moments(
    ds: PathDataset,
    mp: ModelParams,
    spec: Optional[MomentSpec] = None,
) -> Dict[str, float]:
    """Compute a dict of moments from simulated trajectories."""
    spec = spec or build_default_moment_spec()

    k = ds.k_curr
    k1 = ds.k_next
    z = ds.z_curr
    z1 = ds.z_next

    # implied investment: I_t = k_{t+1} - (1-delta)k_t
    I = k1 - (1.0 - mp.delta) * k

    logz = np.log(np.maximum(z, 1e-12))
    logz1 = np.log(np.maximum(z1, 1e-12))
    dlogz = logz1 - logz

    # Implied innovations from the candidate AR(1) parameter rho:
    #   eps_hat_{t+1} = log z_{t+1} - rho * log z_t
    eps_hat = logz1 - (mp.rho * logz)

    logk = np.log(np.maximum(k, mp.k_min))
    logk1 = np.log(np.maximum(k1, mp.k_min))
    dlogk = logk1 - logk

    I_over_k = I / np.maximum(k, mp.k_min)

    out: Dict[str, float] = {}
    for name in spec.names:
        if name == "corr_logz_t1_t":
            out[name] = _corr(logz1, logz)
        elif name == "var_logz":
            out[name] = float(np.var(logz))
        elif name == "var_dlogz":
            out[name] = float(np.var(dlogz))
        elif name == "mean_eps_hat":
            out[name] = float(np.mean(eps_hat))
        elif name == "var_eps_hat":
            out[name] = float(np.var(eps_hat))
        elif name == "mean_I_over_k":
            out[name] = float(np.mean(I_over_k))
        elif name == "var_I_over_k":
            out[name] = float(np.var(I_over_k))
        elif name == "var_dlogk":
            out[name] = float(np.var(dlogk))
        elif name == "corr_Ioverk_logz":
            out[name] = _corr(I_over_k, logz)
        else:
            raise ValueError(f"Unknown moment: {name}")
    return out


def make_identity_weight_matrix(J: int) -> np.ndarray:
    """Start with W = I (stable)."""
    return np.eye(J, dtype=np.float64)
